name: Update random feed item

on:
  schedule:
    - cron: "0 */6 * * *"   # запуск каждые 6 часов
  workflow_dispatch:         # ручной запуск

permissions:
  contents: write

jobs:
  update-random-item:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1       # берем только последний коммит, меньше шансов, что git у GitHub упадёт

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run script to fetch random item
        run: node fetch_random_from_feed.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add random_item.json || echo "Nothing to add"
          git commit -m "Update random_item.json [skip ci]" || echo "No changes to commit"
          git push || echo "Nothing to push"
